name: 'Accesibility'
description: 'Installs and configures common accesibility modules.'
type: 'recipe'

install:
  # Install primary module.
  - username_enumeration_prevention
  - title_a11y

# config:
#   import:
#     password_policy:
#       # Add Password Policy Settings
#       - password_policy.settings
#       # Add Password Policy fields.
#       - field.field.user.user.field_last_password_reset
#       - field.field.user.user.field_password_expiration
#       - field.field.user.user.field_password_test
#       - field.field.user.user.field_pending_expire_sent
#       - field.storage.user.field_last_password_reset
#       - field.storage.user.field_password_expiration
#       - field.storage.user.field_password_test
#       - field.storage.user.field_pending_expire_sent
#       # The 90-day policy is imported by default from this recipe's config folder.
#     user:
#       - user.settings
#     admin_toolbar:
#       - admin_toolbar.settings
#     admin_toolbar_tool:
#       - admin_toolbar_tool.settings
#   actions:
#     # Adds Two new fields to the user form. The third field is hidden by default.
#     core.entity_form_display.user.user.default:
#       setComponents:
#         -
#           name: field_last_password_reset
#           options:
#             type: datetime_default
#             weight: 4
#             region: content
#             settings: {  }
#             third_party_settings: {  }
#         -
#           name: field_password_expiration
#           options:
#             type: boolean_checkbox
#             weight: 3
#             region: content
#             settings:
#               display_label: true
#             third_party_settings: {  }
#         -
#           name: field_password_test
#           options:
#             type: boolean_checkbox
#             weight: 3
#             region: content
#             settings:
#               display_label: true
#             third_party_settings: {  }
