name: 'Accesibility'
description: 'Installs and configures common accesibility modules.'
type: recipe

install:
  # Install primary module.
  - title_a11y
  - editoria11y
  - menu_link_attributes
  - block_aria_landmark_roles
  - linkit

config:
  strict: false
  import:
    linkit: '*'
  actions:
    filter.format.basic_html:
      setFilterConfig:
        instance_id: linkit
        configuration:
          id: linkit
          status: true
          provider: linkit
          weight: 0
          settings:
            title: true
            profile: default
    filter.format.full_html:
      setFilterConfig:
        instance_id: linkit
        configuration:
          id: linkit
          status: true
          provider: linkit
          weight: 0
          settings:
            title: true
            profile: default
